library(tidyr)
library(dplyr)
library(ggplot2)
library(stringr)
library(readr)
library(shiny)
library(plotly)
library(leaflet)
library(RColorBrewer)
library(colorRamps)
library(viridis)
library(htmltools)
library(forcats)
library(geojsonio)
shapeurl <- "https://raw.githubusercontent.com/johan/world.geo.json/master/countries.geo.json"
WorldCountry <- geojson_read(shapeurl, what = "sp")
data1.2 <- read.csv("Finalized.csv")
data2 <- read.csv("Finalized2.csv")